{% set version = '1.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dbplyr
  version: {{ version|replace("-", "_") }}

source:
  fn: dbplyr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dbplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dbplyr/dbplyr_{{ version }}.tar.gz
  sha256: b348e7a02623f037632c85fb11be16c40c01755ae6ca02c8c189cdc192a699db

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, covr, knitr, Lahman (>= 5.0.0), nycflights13 (>= 0.2.2), rmarkdown, RMariaDB (>= 1.0.2), RMySQL (>= 0.10.11), RPostgreSQL (>= 0.4.1), RSQLite (>= 2.0), testthat (>= 2.0.0)
requirements:
  build:

  host:
    - r-base
    - r-dbi >=0.7
    - r-r6 >=2.2.2
    - r-assertthat >=0.2.0
    - r-dplyr >=0.7.4
    - r-glue >=1.2.0
    - r-purrr >=0.2.4
    - r-rlang >=0.1.6
    - r-tibble >=1.4.1
    - r-tidyselect >=0.2.2

  run:
    - r-base
    - r-dbi >=0.7
    - r-r6 >=2.2.2
    - r-assertthat >=0.2.0
    - r-dplyr >=0.7.4
    - r-glue >=1.2.0
    - r-purrr >=0.2.4
    - r-rlang >=0.1.6
    - r-tibble >=1.4.1
    - r-tidyselect >=0.2.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dbplyr')"           # [not win]
    - "\"%R%\" -e \"library('dbplyr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/tidyverse/dbplyr
  license: MIT + file LICENSE
  summary: A 'dplyr' back end for databases that allows you to work with  remote database tables
    as if they are in-memory data frames. Basic features works with any database that
    has a 'DBI' back end; more advanced features  require 'SQL' translation to be provided
    by the package author.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - mingwandroid

# The original CRAN metadata for this package was:

# Type: Package
# Package: dbplyr
# Title: A 'dplyr' Back End for Databases
# Version: 1.2.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("Edgar", "Ruiz", role = "aut"), person("RStudio", role = c("cph", "fnd")) )
# Description: A 'dplyr' back end for databases that allows you to work with  remote database tables as if they are in-memory data frames. Basic features works with any database that has a 'DBI' back end; more advanced features  require 'SQL' translation to be provided by the package author.
# License: MIT + file LICENSE
# URL: https://github.com/tidyverse/dbplyr
# BugReports: https://github.com/tidyverse/dplyr/issues
# Depends: R (>= 3.2)
# Imports: assertthat (>= 0.2.0), DBI (>= 0.7), dplyr (>= 0.7.4), glue (>= 1.2.0), methods, purrr (>= 0.2.4), R6 (>= 2.2.2), rlang (>= 0.1.6), tibble (>= 1.4.1), tidyselect (>= 0.2.2), utils
# Suggests: bit64, covr, knitr, Lahman (>= 5.0.0), nycflights13 (>= 0.2.2), rmarkdown, RMariaDB (>= 1.0.2), RMySQL (>= 0.10.11), RPostgreSQL (>= 0.4.1), RSQLite (>= 2.0), testthat (>= 2.0.0)
# VignetteBuilder: knitr
# LazyData: yes
# RoxygenNote: 6.0.1
# Collate: 'cache.r' 'compat-purrr.R' 'data-lahman.r' 'data-nycflights13.r' 'db-compute.R' 'db-mysql.r' 'db-odbc-access.R' 'db-odbc-hive.R' 'db-odbc-impala.R' 'db-odbc-mssql.R' 'db-odbc-oracle.R' 'db-odbc-redshift.R' 'db-odbc-teradata.R' 'db-postgres.r' 'db-roracle.R' 'db-sqlite.r' 'dbi-s3.r' 'dbplyr.R' 'do.r' 'explain.r' 'utils.r' 'ident.R' 'lazy-ops.R' 'memdb.R' 'partial-eval.r' 'query.r' 'remote.R' 'schema.R' 'simulate.r' 'sql-build.R' 'sql-escape.r' 'sql-expr.R' 'sql-generic.R' 'sql-optimise.R' 'sql-query.R' 'sql-render.R' 'sql.R' 'src-sql.r' 'src_dbi.R' 'tbl-lazy.R' 'tbl-sql.r' 'test-frame.R' 'testthat.r' 'translate-sql-helpers.r' 'translate-sql-window.r' 'translate-sql-base.r' 'translate-sql-clause.r' 'translate-sql-odbc.R' 'translate-sql-paste.R' 'translate-sql.r' 'utils-format.r' 'window.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2018-02-19 15:55:28 UTC; hadley
# Author: Hadley Wickham [aut, cre], Edgar Ruiz [aut], RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-02-19 19:40:06 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
