travis:
  secure:
    BINSTAR_TOKEN: nuf+aeCxe4vURo2seejDoiFMK4GRvsFQrJ2C5VXmVcEmlF5xGajcye3+HlerIwZ5pWZhr2tqAqWRZivkgBAyKFQOOBoZ1k6sJfhVKwe2TPAgRwQIFFuMDrH3ipOAYhUyJEwCuChsOLyVTc5QN06uIfEcKXMIyuFJAMRqvbQ+IjVZ4IqS26D2b43HTNoPo3mClKfLqAkStAY2SFMykEmjnHj42P33wqVL+BJhUamC02CraMfzWikEHBDIozGG2HzGZ0DcxYh4bKUWTrcvoqOfoBQc/LRBnxdXol+Huy6FVPVKvL5LmEi2kkgNJ61BsKGXCxmx6uwnPkLvTvc4VxcEFWUN9DzSqHc7gDePdk9beMFXl0B2paJCDf+quhrvWUkxPOzLz/0qx2sL3Eb7byA0fG9fMA5TFg5DhJ45KEXW1UgwhwnQ7t0C1/mHADa1npB6BEy9/ZCgXEVq4cT1/fnMGqiE4Y0PEPFmRvkjO27LjVAQ3WVfiBz4mq8HS6087Jwc/GZ89TkTKGI/WxV9iHVRW5e+yGCn6mkm2VmxeWxcqrGemw/YjF/fOjMO7FnSWGbNcK8J1eWRl3SRPCVx/ms8WynwksjH1Eip7SYvihRLnf+iG3Op+dX/TD4ac3ouvRjUdnikkDjRu6DZ3qW1zdhrUdDaiocMANDu/a3yQ1wOJlA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
